### ISSUE TITLE
Change Enrichment Plot Positive Color

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#53]
Jill really doesn't like the pink the current positive plot is using, think we could change it to something more along the lines of an ~#F00000~ #EF553B?

**Comment by KwatME** [comment]
Sure

**Comment by ACastanza** [comment]
Thanks! Although maybe #EF553B would be better, I think that's what plotly uses by default in some of it's categorical assignments. Maybe also #636EFA for negative to be consistent with that?

**Comment by KwatME** [comment]
![Unknown-36](https://user-images.githubusercontent.com/7741548/158917778-94b9c699-ede4-47f0-b859-93e21537a202.png)

**Comment by ACastanza** [comment]
Looks like this might not be active in the 0.9.0 build?

**Comment by KwatME** [comment]
Do you not see something like this?
![Unknown-38](https://user-images.githubusercontent.com/7741548/159326454-dfe04e36-9a15-4a53-8ae7-ea59e3af1466.png)
 
I tried the categorical colors (1st figure above) but they looked darker than I hoped and there were many plots with those colors, so I wanted to be a bit different and have GSEA colors instead of defaults used by the majority. We can explore more colors for sure. I just made the current ones more bright and less pink as well as color-blindness-friendly.

**Comment by ACastanza** [comment]
The colors in the comment you posted before closing the issue were good, the new ones that you ended up going with are not, they get the same objection to the color combination that the original ones got.

**Comment by KwatME** [comment]
https://statisticsglobe.com/wp-content/uploads/2019/09/figure-2-default-ggplot2-colors-4-colors-palette.png

**Comment by KwatME** [comment]
Let's pick a new set of 4 colors.
